$:
  vscode:
    - docker:
        build: .ide/Dockerfile
      services:
        - vscode
        - docker

feat*:
  push:
    - services:
        - docker
      stages:
        - name: sync to github
          imports: https://cnb.cool/spencezhang/my-keys/-/blob/main/env.yml
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/logzh/${CNB_REPO_NAME}.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}

        - name: set frontend docker tag
          ifModify:
            - frontend/*
            - .cnb.yml
          script: echo -n "${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:frontend.${CNB_BRANCH}.${CNB_COMMIT_SHORT}"
          exports:
            info: FRONTEND_IMAGE_TAG
        - name: build frontend image
          ifModify:
            - frontend/*
            - .cnb.yml
          script: docker build -t $FRONTEND_IMAGE_TAG . -f frontend/Dockerfile --target prod
        - name: push frontend image
          ifModify:
            - frontend/*
            - .cnb.yml
          script: docker push $FRONTEND_IMAGE_TAG

        - name: set gateway docker tag
          ifModify:
            - backend/*
            - .cnb.yml
          script: echo -n "${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:gateway.${CNB_BRANCH}.${CNB_COMMIT_SHORT}"
          exports:
            info: GATEWAY_IMAGE_TAG
        - name: build gateway image
          ifModify:
            - backend/*
            - .cnb.yml
          script: docker build -t $GATEWAY_IMAGE_TAG . -f backend/Dockerfile
        - name: push gateway image
          ifModify:
            - backend/*
            - .cnb.yml
          script: docker push $GATEWAY_IMAGE_TAG

        - name: set langgraph docker tag
          ifModify:
            - backend/*
            - .cnb.yml
          script: echo -n "${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:langgraph.${CNB_BRANCH}.${CNB_COMMIT_SHORT}"
          exports:
            info: LANGSERVER_IMAGE_TAG
        - name: build langgraph image
          ifModify:
            - backend/*
            - .cnb.yml
          script: docker build -t $LANGSERVER_IMAGE_TAG . -f backend/Dockerfile
        - name: push langgraph image
          ifModify:
            - backend/*
            - .cnb.yml
          script: docker push $LANGSERVER_IMAGE_TAG

        - name: set nginx docker tag
          ifModify:
            - docker/nginx/*
            - .cnb.yml
          script: echo -n "${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:nginx.${CNB_BRANCH}.${CNB_COMMIT_SHORT}"
          exports:
            info: NGINX_IMAGE_TAG
        - name: build nginx image
          ifModify:
            - docker/nginx/*
            - .cnb.yml
          script: docker build -t $NGINX_IMAGE_TAG -f docker/nginx/Dockerfile docker/nginx
        - name: push nginx image
          ifModify:
            - docker/nginx/*
            - .cnb.yml
          script: docker push $NGINX_IMAGE_TAG

        - name: set provisioner docker tag
          ifModify:
            - docker/provisioner/*
            - .cnb.yml
          script: echo -n "${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:provisioner.${CNB_BRANCH}.${CNB_COMMIT_SHORT}"
          exports:
            info: PROVISIONER_IMAGE_TAG
        - name: build provisioner image
          ifModify:
            - docker/provisioner/*
            - .cnb.yml
          script: docker build -t $PROVISIONER_IMAGE_TAG -f docker/provisioner/Dockerfile docker/provisioner
        - name: push provisioner image
          ifModify:
            - docker/provisioner/*
            - .cnb.yml
          script: docker push $PROVISIONER_IMAGE_TAG